from typing import TypeVar, Generic
T = TypeVar("T")
class Array(Generic[T]):
    def __init__(self, size: int) -> None: ...
    def get(self, index: int) -> T:...
    def set(self, index: int, value: T) -> None:...
    def __getitem__(self, index: int) -> T:...
    def __setitem__(self, index: int, value: T) -> None:...
    def __len__(self) -> int:...